src/httpapi.web/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Web.Mvc;
using httpapi.web.Models;

namespace httpapi.web.Controllers
{
    public class ClientController : Controller
    {
        public ActionResult Test()
        {
            ViewBag.Message = TempData["Message"];
            ViewBag.Deleted = TempData["Deleted"] ?? false;
            ViewBag.Updated = TempData["Updated"] ?? false;
            ViewBag.ExistingFormValues = GetExistingFormValues().form;
            var apiContent = TempData["APIContent"] as SampleData;
            var content = new Dictionary<string, object>();
            if(apiContent != null)
            {
                content = apiContent.form;
            }
            return View(content);
        }

        [HttpPost]
        public ActionResult Delete(FormCollection data)
        {
            var formUrlEncodedContent = ExtractFormData(data);
            var request = new HttpRequestMessage(HttpMethod.Put, "delete?key=" + data["key"]) { Content = formUrlEncodedContent };
            var response = CreateClient().SendAsync(request).Result;
            var result = response.Content.ReadAsAsync<SampleData>().Result;
            TempData["APIContent"] = result;
            TempData["Deleted"] = true;
            return RedirectToAction("test");
        }

        [HttpPost]
        public ActionResult Put(FormCollection data )
        {
            var formUrlEncodedContent = ExtractFormData(data);
            var request = new HttpRequestMessage(HttpMethod.Put, "put") {Content = formUrlEncodedContent};
            var response = CreateClient().SendAsync(request).Result;
            if(response.IsSuccessStatusCode)
            {
                var result = response.Content.ReadAsAsync<SampleData>().Result;
                TempData["APIContent"] = result;
                TempData["Updated"] = true;
            }
            else
            {
                TempData["Message"] = response.ReasonPhrase;
            }
           
            return RedirectToAction("test");
        }

        private static FormUrlEncodedContent ExtractFormData(FormCollection data)
        {
            var content = new Dictionary<string, string>();
            foreach (var key in data.AllKeys)
            {
                if(key.StartsWith("k"))
                content[key] = data[key];
            }
            var formUrlEncodedContent = new FormUrlEncodedContent(content);
            return formUrlEncodedContent;
        }

        [HttpPost]
        public ActionResult Post(string key, string value)
        {
            var formUrlEncodedContent = new FormUrlEncodedContent( new Dictionary<string, string>() {{key, value}});
            var request = new HttpRequestMessage(HttpMethod.Post, "post") { Content = formUrlEncodedContent };
            var response = CreateClient().SendAsync(request).Result;
            var result = response.Content.ReadAsAsync<SampleData>().Result;
            TempData["APIContent"] = result;
            return RedirectToAction("test");
        }

        private SampleData GetExistingFormValues()
        {
            var client = CreateClient();
            var response = client.GetAsync("get").Result;
            var content = response.Content.ReadAsAsync<SampleData>().Result;
            return content;
        }

        private HttpClient CreateClient()
        {
            var currentUrl = ControllerContext.HttpContext.Request.Url;
            var port = 80;

            // to workaround appharbor limiation
            if (ControllerContext.HttpContext.Request.IsLocal)
            {
                port = currentUrl.Port;
            }
            Uri baseUri = new UriBuilder(currentUrl.Scheme, currentUrl.Host, port).Uri;
            var client = new HttpClient {BaseAddress = baseUri};
            return client;
        }
    }
}

src/httpapi.web/Views/Client/Index.cshtml
@model  Dictionary<string, object>

<hgroup class="title">
    <h1>HTTP Methods</h1>
    <h2>POST, PUT, DELETE</h2>
</hgroup>


@using (Html.BeginForm("Put", "Client"))
{
    @Html.AntiForgeryToken()
    <fieldset>
        <legend>PUT</legend>
        <ol>
            @foreach (var key in Model.Keys)
            { 
                <li>
                    @Html.Label(key)
                    @Html.TextBox(key, Model[key])
                    <input id="put" type="submit" name="put" value="PUT" />
                </li> 
            }
        </ol>
    </fieldset>
}

@using (Html.BeginForm("Delete", "Client"))
{
    @Html.AntiForgeryToken()
    <fieldset>
        <legend>DELETE</legend>
        <ol>
            @foreach (var key in Model.Keys)
            { 
                <li>
                    <label id="lblKey">@key - @Model[key]</label>
                    @Html.Hidden("key", key)
                    <input id="delete" type="submit" name="delete" value="DELETE" />
                </li> 
            }
        </ol>

    </fieldset>
}


@using (Html.BeginForm("Post", "Client"))
{
    @Html.AntiForgeryToken()
    <fieldset>
        <legend>POST</legend>
        <ol>
            @foreach (var key in Model.Keys)
            { 
                <li>
                    @Html.Label(key)
                    @Html.TextBox(key, Model[key])
                </li> 
            }
        </ol>
        <input id="add" type="submit" name="add" value="Add" />

    </fieldset>
}

src/httpapi.web/Views/Client/test.cshtml
@model  Dictionary<string, object>

<hgroup class="title">
    <h1>HTTP Methods Test Client</h1>
    <h3 style="float: right"><a href="/Index">Api Home</a></h3>
</hgroup>

<section class="featured">
    <div class="content-wrapper">
        <h3 style="float: right"><a href="/client/test">Reset</a></h3>
        <h2>PUT</h2>
        <h4>@ViewBag.Message</h4>
        @using (Html.BeginForm("Put", "Client"))
        {
            @Html.AntiForgeryToken()
            <fieldset>
                <legend>PUT</legend>
                @if (ViewBag.Updated)
                {
                    <h6>New Form Key/Value Pairs: </h6>
                    <ol>
                        @foreach (var key in Model.Keys)
                        { 
                            <li>
                                <label id="lblKey">@key - @Model[key]</label>
                            </li> 
                        }
                    </ol>
                    <ol>
                        @foreach (var key in Model.Keys)
                        { 
                            <li>
                                @Html.Label(key)
                                @Html.TextBox(key, Model[key])

                            </li> 
                        }
                    </ol>
                }
                else
                {
                    <ol>
                        @foreach (var key in ViewBag.ExistingFormValues.Keys)
                        { 
                            <li>
                                <label id="lblKey">@key</label>
                                <input type="text" id="@key" name="@key" value="@ViewBag.ExistingFormValues[key]"/>
                            </li> 
                        }
                    </ol>
                }
                <input id="put" type="submit" name="put" value="PUT" />
            </fieldset>
        }
    </div>
</section>
<p></p>
<section class="featured">
    <div class="content-wrapper">
         <h3 class="clear-fix" style="float: right"><a href="/client/test">Reset</a></h3>
        <h2>DELETE</h2>
       
        <h4>@ViewBag.Message</h4>
        @using (Html.BeginForm("Delete", "Client"))
        {
            @Html.AntiForgeryToken()
            <fieldset>
                <legend>DELETE</legend>
                @if (!ViewBag.Deleted)
                {
                    <ol>
                        @foreach (var key in ViewBag.ExistingFormValues.Keys)
                        {
                            <li>
                                <label id="lblKey">@key - @ViewBag.ExistingFormValues[key]</label>
                                <input id="delete" type="submit" name="delete" value="DELETE" />
                            </li>
                        }
                    </ol>
                }

            </fieldset>
        }
    </div>
</section>
<p></p>
<section class="featured">
    <div class="content-wrapper">
        <h3 style="float: right"><a href="/client/test">Reset</a></h3>
        <h2>POST</h2>
        
        @using (Html.BeginForm("Post", "Client"))
        {
            @Html.AntiForgeryToken()
            <fieldset>
                <legend>POST</legend>
                <h4>@ViewBag.Message</h4>
                <h6>Existing Form Key/Value Pairs: </h6>
                <ol>
                    @foreach (var key in ViewBag.ExistingFormValues.Keys)
                    { 
                        <li>
                            <label id="lblKey">@key - @ViewBag.ExistingFormValues[key]</label>
                        </li> 
                    }
                </ol>
                @if (Model.Count > 0 && !ViewBag.Deleted && !ViewBag.Updated)
                {
                    <h6>New Form Key/Value Pairs: </h6>
                    <ol>
                        @foreach (var key in Model.Keys)
                        { 
                            <li>
                                <label id="lblKey">@key - @Model[key]</label>
                            </li> 
                        }
                    </ol>
                }

                <h6>Post new key value pair</h6>
                <label id="key">Key</label>
                @Html.TextBox("key")
                <label id="Value">Value</label>
                @Html.TextBox("value")
                <input id="add" type="submit" name="add" value="Add" />
            </fieldset>
        }
    </div>
</section>
